version: '3.8'
services:
  mongo:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    external: false